name: Cloudcamp CI
on:
  push:

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
      - name: "checkout"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #Version 4.2.2

      - name: "print files"
        run: |
          ls
          pwd
      - name: Instalaci贸n de terraform
        uses: hashicorp/setup-terraform@v3
      - run: terraform version

  job-depends:
    runs-on: ubuntu-latest
    needs: [hello_world]
    steps:
      - run: echo "${{ github.actor }}"
  terraform:
    name: Terraform CI
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: "checkout"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #Version 4.2.2

      - name: Instalaci贸n de terraform
        uses: hashicorp/setup-terraform@v3

      - name: Ejecuci贸n terraform init
        run: terraform init
      - name: Ejecuci贸n terraform plan
        run: terraform plan
